[versions]
agp = "9.0.0"
android-compileSdk = "36"
android-minSdk = "24"
#android-targetSdk = "36"
kotlin = "2.3.10"
ktor = "3.4.1"
skie-version = "0.10.10"


[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
android-ktor = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ios-ktor = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
skie = { id = "co.touchlab.skie", version.ref = "skie-version" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mavenPublish = { id = "maven-publish"}
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }

[bundles]
ktor = ["ktor-core", "ktor-negotiation", "ktor-serialization"]